/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PersonalDetails: typeof import('./components/PersonalDetails.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./components/Skills.vue')['default']
    WorkHistory: typeof import('./components/WorkHistory.vue')['default']
  }
}
